      - name: Ejecutar scraper
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python3 src/scraper.py
